//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SKUD.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class employeer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employeer()
        {
            this.events = new HashSet<@event>();
        }
    
        public int employeer_id { get; set; }
        public string surname { get; set; }
        public string name { get; set; }
        public string patronomyc { get; set; }
        public string notes { get; set; }
        public Nullable<int> pass_id { get; set; }
        public byte[] photo { get; set; }
    
        public virtual account account { get; set; }
        public virtual department department { get; set; }
        public virtual post post { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<@event> events { get; set; }
        public virtual pass pass { get; set; }
    }
}
