//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SKUD.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FXDBEntities : DbContext
    {
        public FXDBEntities()
            : base("name=FXDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account> accounts { get; set; }
        public virtual DbSet<department> departments { get; set; }
        public virtual DbSet<employeer> employeers { get; set; }
        public virtual DbSet<@event> events { get; set; }
        public virtual DbSet<event_type> event_type { get; set; }
        public virtual DbSet<guest_event> guest_event { get; set; }
        public virtual DbSet<pass> passes { get; set; }
        public virtual DbSet<post> posts { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<guest> guests { get; set; }
        public virtual DbSet<guest_type> guest_type { get; set; }
    }
}
